### ISSUE TITLE
How to pass arguments to the_widget function?

### ISSUE THREAD

**Issue by KingMatrix1989** [wordpress-parsi/wp-parsidate#11]
سلام. وقت بخیر.

در بخشی از کد یک قالب، برای نمایش بایگانی از کد زیر استفاده شده:

`the_widget( 'WP_Widget_Archives', 'dropdown=1&title=' . esc_html__( 'Archives', 'sparkling' ), "after_title=</h2>$archive_content" )`

من قصد دارم با استفاده از همین تابع، بایگانی شمسی رو فراخوانی کنم. لذا کد رو به صورت زیر تغییر میدم:

`the_widget( 'parsidate_archive', 'parsidate_archive_list=1&title=' . esc_html__( 'Archives', 'sparkling' ), "after_title=</h2>$archive_content" );`

فراخوانی بایگانی شمسی انجام میشه ولی پارامتر نمایش به صورت لیست گویا به تابع منتقل نمیشه.

چطور میتونم نمایش رو به صورت لیست انجام بدم؟

**Comment by mostafasoufi** [comment]
@man4toman Do you have any idea?

**Comment by lord-viper** [comment]
از همون dropdown=1 استفاده کنید ببینید درست میشه

**Comment by hectorfarahani** [comment]
@skmohammadi You can use the below code:
```the_widget( 'parsidate_archive', 'parsidate_archive_list=1&parsidate_archive_title=' . esc_html__( 'Archives', 'sparkling' ), "after_title=</h2>$archive_content" );```

Note: 
`parsidate_archive_list` used to show archive as dropdown list.
`parsidate_archive_title` used instead of `title` to show title of widget.

Also `parsidate_archive_count` is available to show count of posts, and `parsidate_archive_type` to change type of archive to **Daily** or **Yearly**.
