### ISSUE TITLE
Accept password with Persian characters

### ISSUE THREAD

**Issue by zarei-dev** [wordpress-parsi/wp-parsidate#137]
Sample:
https://wordpress.org/plugins/persian-password

I can implement this feature with a switch for Enable/Disable.
What do you think?

**Comment by man4toman** [comment]
Hi @zarei-dev 

Thanks for your suggestion, honestly we have important tasks in our To-Do list,  specially WooCommerce related.

But I'll put this one in next-release list.

**Comment by hamidrezayazdani** [comment]
Hi @zarei-dev 

Thank you for your suggestion. As you have pointed out the security problem of this method in the description of the plugin that you have developed yourself, unfortunately it is not possible to do this.

Instead, we can add a new function so that if users need to activate it, passwords with Persian numbers and characters can be changed during registration or login to the user account and saved in English format in the database. In this case, we will not have a security problem.

The challenge of this task is that there are many plugins and form builders that change the login information or use different methods, and this problem makes the development time consuming compared to the efficiency of this feature.

So, as a result, I'll cancel this task from issues for the time being so that we can develop it at a suitable time.

If you have something else in mind, feel free to bring it up
