### ISSUE TITLE
مشکل ایکون

### ISSUE THREAD

**Issue by bihovi584om** [wordpress-parsi/wp-parsidate#177]
سلام همچنان مشکل ایکون ها پابرجاست طبق بررسی که انجام دادم توی اخرین نسخه پارسی دیت هم مشکل ایکون ها وجود داره
ایکون های تغییر تاریخ
اینجا گزارش داده بودم

https://github.com/wordpress-parsi/wp-parsidate/issues/171

**Comment by bihovi584om** [comment]
نمیتونید از انتخابگر تاریخ افزونه زیر استفاده کنید بسیار بهتر طراحی شده و همچنین باگی ندیدم حداقل توی ظاهرش (منظورم فقط قسمت انتخابگر تاریخش هست برای زمانبندی و انتشار پست ها) و الباقی قسمت ها مثل سابق باشه
https://github.com/wpvar/wp-shamsi

**Comment by hamidrezayazdani** [comment]
Please clear your browser cache before testing. The icons are displayed for me in the latest version.

![Screenshot 2024-03-11 at 13-29-34](https://github.com/wordpress-parsi/wp-parsidate/assets/40775953/0a5fa903-b082-4a56-ab82-81e8c8f1338a)

Regarding the plugin you introduced, this plugin has been removed from the WordPress repository due to security issues. We do not accept such risk for ourselves and our users.
